Eliminate deprecated method call to fix build error
```
> Task :spring-boot-project:spring-boot-actuator:compileJava
/home/runner/work/spring-boot/spring-boot/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/web/reactive/AbstractWebFluxEndpointHandlerMapping.java:527: warning: [deprecation] check(Supplier<Authentication>,T) in AuthorityAuthorizationManager has been deprecated
				.check(this::getAuthentication, null)
				^
  where T is a type-variable:
    T extends Object declared in class AuthorityAuthorizationManager
error: warnings found and -Werror specified
1 error
1 warning

> Task :spring-boot-project:spring-boot-actuator:compileJava FAILED
```

Caused by changes at Spring Security side, see https://github.com/spring-projects/spring-security/commit/9ce5a76e8c2322a07f04923e8ce92d62cc7a8b0d#diff-8c62a1a24d0860e1da929cdb7cdbf50a8e7daa565fd03f05673299917891f33b