Catch Throwable instead of Exception in Spring Application
...so that application startup that fails because of an Error (for
instance NoClassDefFoundError) won't be swallowed.

Fixes gh-1645