Add Flyway 12.0 compatibility handling in FlywayAutoConfiguration
In Flyway 12.0, the `cleanOnValidationError` property was removed.
This commit catches `NoSuchMethodError` to maintain compatibility with
Flyway 12.0

See gh-49059

Signed-off-by: Dmytro Nosan <dimanosan@gmail.com>