Upgrade gradle to 8.1.1
Adapt gradle API changes:
1. Gradle 8 does no longer allow classifier inside Jar task. archiveClassifier must be used instead.
2. Upgrade nohttp to fix java.lang.NoSuchMethodError: 'void org.gradle.api.reporting.SingleFileReport.setDestination(org.gradle.api.provider.Provider)'
3. GradlePropertiesController::loadGradlePropertiesFrom signature changed