Remove compatibility code for EOL dependency versions
Remove NoSuchMethodError catch blocks and reflective fallbacks for
dependency versions that are no longer supported:

- Flyway < 7.0 and < 9.14 (managed version: 12.4.0)
- Tomcat 8.5/9.0 (Boot 4.x uses Jakarta EE)
- Hazelcast 4 (managed version: 5.5.0)
- Jetty 10 (managed version: 12.1.8)

Signed-off-by: Sebastien Tardif <sebtardif@ncf.ca>