Fixed NoClassDefFoundError by optional dependency
The BeanDefinitionLoader defines a field with the optional type `GroovyBeanDefinitionReader`. Since the JVM does not support optional typing, this causes a `ClassNotDefFoundError` when the class is accessed by reflection where all member types are resolved by the JVM. In order to avoid error, the optional type must only be referenced inside of byte code. The fix resolves this by casting the type within any accessing method's body.